version: '3.9'

services:
  # 1. Backend NestJS
  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    image: database-analyzer/backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - app-net

  # 2. Microservicio FastAPI
  fastapi:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    image: database-analyzer/fastapi:latest
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - app-net

  # 3. Frontend Angular
  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    image: database-analyzer/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-net

  # 4. Ollama (LLM local)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped
    networks:
      - app-net

volumes:
  ollama_storage:

networks:
  app-net:
