version: "3.9"

services:
  nats-transport:
    image: nats:2.11.8

  api-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-transport:4222

  analyze-orchestrate:
    build: 
      context: ./analysis-orchestrator
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-transport:4222

  metadata-service:
    build: 
      context: ./metadata-service
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-transport:4222
